// ============================================================
// DOCTEMPLATES.JS
// Template HTML untuk semua dokumen cetak: invoice, rapor/laporan,
// lembar absensi, legger bulanan. Dipakai bersama oleh pages/invoice.js,
// pages/reports.js, dan pages/documents.js supaya tidak ada kode duplikat.
//
// Kalau mau ubah TAMPILAN dokumen (misalnya tata letak invoice),
// cukup ubah di sini - otomatis berlaku di semua halaman yang pakai.
// ============================================================
import { escapeHtml, rupiah, fmtDate, avg, todayISO } from './utils.js';
import * as store from './dataStore.js';

export function brandedDocHeader(settings, title, subtitle = '') {
  return `<div class="docHead"><div class="docBrand"><div class="docLogo">${
    settings.logoData ? `<img src="${settings.logoData}" alt="logo">` : 'LOGO'
  }</div><div><h2>${escapeHtml(
    settings.institutionName || 'Nama Lembaga Les'
  )}</h2><p>${escapeHtml(
    settings.address || 'Alamat lembaga les'
  )}</p><p>${escapeHtml(
    settings.phone || ''
  )}</p></div></div><div class="docTitle"><h1>${escapeHtml(
    title
  )}</h1><p>${escapeHtml(
    subtitle
  )}</p><span class="docPill">LesKu · Hasilin</span></div></div>`;
}

export function docFooter() {
  return `<div class="docFoot"><span>Generated by LesKu · powered by Hasilin</span><span>${fmtDate(
    todayISO()
  )}</span></div>`;
}

export function levelFromScore(v) {
  v = Number(v || 0);
  if (v >= 86) return 'BSB - Berkembang Sangat Baik';
  if (v >= 70) return 'BSH - Berkembang Sesuai Harapan';
  if (v >= 55) return 'MB - Mulai Berkembang';
  if (v > 0) return 'BB - Belum Berkembang';
  return '-';
}

export function aspectComment(k, v) {
  v = Number(v || 0);
  if (!v) return 'Belum ada nilai pada periode ini.';
  if (v >= 86) return `${k} sangat baik dan perlu dipertahankan.`;
  if (v >= 70) return `${k} berkembang baik dengan latihan rutin.`;
  if (v >= 55) return `${k} mulai berkembang dan masih perlu pendampingan.`;
  return `${k} membutuhkan penguatan dasar secara bertahap.`;
}

export function makeNarrative(s, ass, lrn, att, type) {
  if (lrn.length && lrn[lrn.length - 1].parentNote)
    return lrn[lrn.length - 1].parentNote;
  const a = ass[ass.length - 1] || {};
  const score = Math.round(
    avg(
      [
        'readingScore',
        'writingScore',
        'countingScore',
        'focusScore',
        'independenceScore',
      ].map((k) => a[k])
    ) || 0
  );
  if (type === 'Rapor Akhir Periode')
    return `${
      s.name || 'Ananda'
    } menunjukkan perkembangan belajar dengan rata-rata capaian ${
      score || '-'
    }. Kekuatan utama dan area pendampingan perlu terus dipantau melalui latihan membaca, menulis, dan berhitung yang konsisten.`;
  if (score >= 80)
    return `${
      s.name || 'Ananda'
    } menunjukkan perkembangan yang baik dan semakin percaya diri mengikuti kegiatan belajar.`;
  if (score >= 65)
    return `${
      s.name || 'Ananda'
    } mulai berkembang dengan baik, namun masih membutuhkan latihan rutin agar capaian belajar lebih stabil.`;
  return `${
    s.name || 'Ananda'
  } masih memerlukan pendampingan lebih intensif, terutama pada materi dasar calistung dan konsentrasi belajar.`;
}

function scoreSummary(ass) {
  const latest = ass[ass.length - 1] || {};
  return {
    latest,
    scores: {
      Membaca: Math.round(
        avg(ass.map((a) => a.readingScore)) || latest.readingScore || 0
      ),
      Menulis: Math.round(
        avg(ass.map((a) => a.writingScore)) || latest.writingScore || 0
      ),
      Berhitung: Math.round(
        avg(ass.map((a) => a.countingScore)) || latest.countingScore || 0
      ),
      Fokus: Math.round(
        avg(ass.map((a) => a.focusScore)) || latest.focusScore || 0
      ),
      Kemandirian: Math.round(
        avg(ass.map((a) => a.independenceScore)) ||
          latest.independenceScore ||
          0
      ),
    },
  };
}

function attendanceSummaryOf(att) {
  return {
    Hadir: att.filter((a) => a.status === 'Hadir').length,
    Izin: att.filter((a) => a.status === 'Izin').length,
    Sakit: att.filter((a) => a.status === 'Sakit').length,
    Alpha: att.filter((a) => a.status === 'Alpha').length,
    Terlambat: att.filter((a) => a.status === 'Terlambat').length,
    Reschedule: att.filter((a) => a.status === 'Reschedule').length,
  };
}

/** Dipakai di halaman Invoice (tampilan .invoicePreview) */
export async function invoiceHTML(p) {
  const [students, classes, settings] = await Promise.all([
    store.list('students'),
    store.list('classes'),
    store.getSettings(),
  ]);
  const s = students.find((x) => x.id === p.studentId) || {};
  const c = classes.find((x) => x.id === p.classId) || {};
  const remain = Number(p.amount || 0) - Number(p.paid || 0);
  return `<div class="invoicePreview"><div class="invoiceTop"><div style="display:flex;gap:14px;align-items:center"><div class="invoiceLogo">${
    settings.logoData ? `<img src="${settings.logoData}" alt="logo">` : 'LOGO'
  }</div><div><b style="font-size:19px">${escapeHtml(
    settings.institutionName || 'Nama Lembaga Les'
  )}</b><div class="subtle">${escapeHtml(
    settings.address || 'Alamat lembaga'
  )}</div><div class="subtle">${escapeHtml(
    settings.phone || ''
  )}</div></div></div><div style="text-align:right"><div class="invoiceTitle">INVOICE</div><div>${escapeHtml(
    p.invoiceNo || '-'
  )}</div><div>${fmtDate(
    p.date
  )}</div></div></div><div class="grid forms"><div><b>Ditagihkan kepada</b><p>${escapeHtml(
    s.name || '-'
  )}<br>${escapeHtml(s.parentName || '-')}<br>${escapeHtml(
    s.parentPhone || '-'
  )}</p></div><div><b>Detail Les</b><p>${escapeHtml(
    c.name || '-'
  )}<br>${escapeHtml(p.packageType || '-')}<br>Periode: ${escapeHtml(
    p.period || '-'
  )}</p></div></div><table class="invoiceTable"><thead><tr><th>Deskripsi</th><th>Nominal</th></tr></thead><tbody><tr><td>Biaya les ${escapeHtml(
    p.period || ''
  )}</td><td>${rupiah(
    p.amount
  )}</td></tr><tr><td>Sudah dibayar</td><td>${rupiah(
    p.paid
  )}</td></tr><tr><td>Sisa pembayaran</td><td>${rupiah(
    remain
  )}</td></tr></tbody></table><div class="totalLine"><div class="totalBox"><div style="display:flex;justify-content:space-between"><b>Status</b><b>${escapeHtml(
    p.status || '-'
  )}</b></div><div style="display:flex;justify-content:space-between;margin-top:8px"><span>Jatuh Tempo</span><span>${fmtDate(
    p.dueDate
  )}</span></div><div style="display:flex;justify-content:space-between;margin-top:8px"><span>Total Tagihan</span><b>${rupiah(
    p.amount
  )}</b></div></div></div><p class="subtle" style="margin-top:18px">${escapeHtml(
    settings.invoiceNote || ''
  )}</p></div>`;
}

/** Dipakai di Pusat Dokumen (tampilan .docPaper bermerek lembaga) */
export async function documentInvoiceHTML(p) {
  const [students, classes, settings] = await Promise.all([
    store.list('students'),
    store.list('classes'),
    store.getSettings(),
  ]);
  const s = students.find((x) => x.id === p.studentId) || {};
  const c = classes.find((x) => x.id === p.classId) || {};
  const remain = Number(p.amount || 0) - Number(p.paid || 0);
  return `<div class="docPaper">${brandedDocHeader(
    settings,
    'INVOICE PEMBAYARAN',
    p.invoiceNo || '-'
  )}<div class="docSection docGrid"><div class="docBox"><b>Ditagihkan kepada</b><p>${escapeHtml(
    s.name || '-'
  )}<br>${escapeHtml(s.parentName || '-')}<br>${escapeHtml(
    s.parentPhone || '-'
  )}</p></div><div class="docBox"><b>Detail Program</b><p>${escapeHtml(
    c.name || '-'
  )}<br>${escapeHtml(p.packageType || '-')}<br>Periode: ${escapeHtml(
    p.period || '-'
  )}</p></div></div><div class="docSection"><table class="docTable"><thead><tr><th>Deskripsi</th><th style="width:220px">Nominal</th></tr></thead><tbody><tr><td>Biaya les ${escapeHtml(
    p.period || ''
  )}</td><td>${rupiah(
    p.amount
  )}</td></tr><tr><td>Sudah dibayar</td><td>${rupiah(
    p.paid
  )}</td></tr><tr><td>Sisa pembayaran</td><td>${rupiah(
    remain
  )}</td></tr></tbody></table></div><div class="docSection" style="display:flex;justify-content:flex-end"><div class="docTotal"><div><span>Status</span><b>${escapeHtml(
    p.status || '-'
  )}</b></div><div><span>Jatuh Tempo</span><b>${fmtDate(
    p.dueDate
  )}</b></div><div><span>Total</span><b>${rupiah(
    p.amount
  )}</b></div></div></div><div class="docBox docSection"><b>Catatan</b><p>${escapeHtml(
    settings.invoiceNote || ''
  )}</p></div><div class="docSign"><div>Orang Tua/Wali<br><br><br><b>(........................)</b></div><div>Admin/Guru<br><br><br><b>(${escapeHtml(
    settings.teacherName || 'Nama Guru'
  )})</b></div></div>${docFooter()}</div>`;
}

/** Dipakai di halaman Reports/Rapor (tampilan .officialReport) */
export async function reportHTML(sid, type, start, end) {
  const [students, assessments, learning, attendance, settings] =
    await Promise.all([
      store.list('students'),
      store.list('assessments'),
      store.list('learning'),
      store.list('attendance'),
      store.getSettings(),
    ]);
  const s = students.find((x) => x.id === sid) || {};
  const ass = assessments.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const lrn = learning.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const att = attendance.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const { latest, scores } = scoreSummary(ass);
  const attendanceSummary = attendanceSummaryOf(att);
  const avgScore = Math.round(avg(Object.values(scores)) || 0);
  const narrative = makeNarrative(s, ass, lrn, att, type);
  const latestLearning = lrn[lrn.length - 1] || {};
  const title =
    type === 'Rapor Akhir Periode' ? 'RAPOR HASIL BELAJAR' : type.toUpperCase();
  const aspectRows = Object.entries(scores)
    .map(
      ([k, v]) =>
        `<tr><td><b>${k}</b><div class="aspectBar"><span style="width:${Math.min(
          100,
          Number(v || 0)
        )}%"></span></div></td><td style="text-align:center;font-weight:900">${
          v || '-'
        }</td><td>${levelFromScore(v)}</td><td>${aspectComment(k, v)}</td></tr>`
    )
    .join('');
  return `<div class="officialReport reportPreview">
    <div class="officialHeader"><div style="display:flex;gap:14px;align-items:center"><div class="invoiceLogo">${
      settings.logoData ? `<img src="${settings.logoData}" alt="logo">` : 'LOGO'
    }</div><div><b style="font-size:20px">${escapeHtml(
    settings.institutionName || 'Nama Lembaga Les'
  )}</b><div class="subtle">${escapeHtml(
    settings.address || 'Alamat lembaga'
  )}</div><div class="subtle">${escapeHtml(
    settings.phone || ''
  )}</div></div></div><div style="text-align:right"><b>LesKu</b><div class="subtle">Powered by Hasilin</div></div></div>
    <div class="officialTitle"><h1>${title}</h1><p>Periode ${fmtDate(
    start
  )} sampai ${fmtDate(end)}</p></div>
    <div class="officialBody">
      <div class="officialMeta"><div class="officialBox"><b>Identitas Siswa</b><table class="officialTable"><tbody><tr><td>Nama</td><td><b>${escapeHtml(
        s.name || '-'
      )}</b></td></tr><tr><td>Orang Tua/Wali</td><td>${escapeHtml(
    s.parentName || '-'
  )}</td></tr><tr><td>Tanggal Lahir</td><td>${fmtDate(
    s.dob
  )}</td></tr></tbody></table></div><div class="officialBox"><b>Ringkasan Periode</b><table class="officialTable"><tbody><tr><td>Rata-rata Nilai</td><td><b>${
    avgScore || '-'
  }</b></td></tr><tr><td>Level Terakhir</td><td>${escapeHtml(
    latest.level || '-'
  )}</td></tr><tr><td>Total Pertemuan Tercatat</td><td>${
    att.length
  }</td></tr></tbody></table></div></div>
      <h3>Rekap Kehadiran</h3>
      <table class="officialTable"><thead><tr><th>Hadir</th><th>Izin</th><th>Sakit</th><th>Alpha</th><th>Terlambat</th><th>Reschedule</th></tr></thead><tbody><tr><td>${
        attendanceSummary.Hadir
      }</td><td>${attendanceSummary.Izin}</td><td>${
    attendanceSummary.Sakit
  }</td><td>${attendanceSummary.Alpha}</td><td>${
    attendanceSummary.Terlambat
  }</td><td>${attendanceSummary.Reschedule}</td></tr></tbody></table>
      <h3>Capaian Perkembangan Calistung</h3>
      <table class="officialTable"><thead><tr><th>Aspek</th><th>Nilai</th><th>Level</th><th>Catatan</th></tr></thead><tbody>${aspectRows}</tbody></table>
      <div class="officialBox"><b>Catatan Perkembangan Guru</b><p>${escapeHtml(
        narrative
      )}</p></div>
      <div class="officialBox" style="margin-top:12px"><b>Materi dan Rekomendasi Latihan</b><p><b>Materi terakhir:</b> ${escapeHtml(
        latestLearning.material || '-'
      )}</p><p><b>Latihan rumah:</b> ${escapeHtml(
    latestLearning.homework ||
      'Latihan singkat 5–10 menit secara rutin dengan pendampingan orang tua.'
  )}</p></div>
      <div class="signatureBox"><div>Orang Tua/Wali<br><br><br><b>(........................)</b></div><div>Guru Les<br><br><br><b>(${escapeHtml(
        settings.teacherName || 'Nama Guru'
      )})</b></div></div>
    </div>
  </div>`;
}

/** Dipakai di Pusat Dokumen (tampilan .docPaper) untuk Laporan Harian/Bulanan/Rapor */
export async function documentReportHTML(sid, type, start, end) {
  const [students, assessments, learning, attendance, settings] =
    await Promise.all([
      store.list('students'),
      store.list('assessments'),
      store.list('learning'),
      store.list('attendance'),
      store.getSettings(),
    ]);
  const s = students.find((x) => x.id === sid) || {};
  const ass = assessments.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const lrn = learning.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const att = attendance.filter(
    (a) => a.studentId === sid && a.date >= start && a.date <= end
  );
  const { latest, scores } = scoreSummary(ass);
  const attendanceSummary = attendanceSummaryOf(att);
  const avgScore = Math.round(avg(Object.values(scores)) || 0);
  const title =
    type === 'Rapor Akhir Periode' ? 'RAPOR HASIL BELAJAR' : type.toUpperCase();
  const narrative = makeNarrative(s, ass, lrn, att, type);
  const latestLearning = lrn[lrn.length - 1] || {};
  const aspectRows = Object.entries(scores)
    .map(
      ([k, v]) =>
        `<tr><td><b>${k}</b><div class="docScore"><span style="width:${Math.min(
          100,
          Number(v || 0)
        )}%"></span></div></td><td style="text-align:center;font-weight:900">${
          v || '-'
        }</td><td>${levelFromScore(v)}</td><td>${aspectComment(k, v)}</td></tr>`
    )
    .join('');
  return `<div class="docPaper">${brandedDocHeader(
    settings,
    title,
    `Periode ${fmtDate(start)} sampai ${fmtDate(end)}`
  )}<div class="docSection docGrid"><div class="docBox"><b>Identitas Siswa</b><table class="docTable"><tbody><tr><td>Nama</td><td><b>${escapeHtml(
    s.name || '-'
  )}</b></td></tr><tr><td>Orang Tua/Wali</td><td>${escapeHtml(
    s.parentName || '-'
  )}</td></tr><tr><td>Tanggal Lahir</td><td>${fmtDate(
    s.dob
  )}</td></tr></tbody></table></div><div class="docBox"><b>Ringkasan Periode</b><table class="docTable"><tbody><tr><td>Rata-rata Nilai</td><td><b>${
    avgScore || '-'
  }</b></td></tr><tr><td>Level Terakhir</td><td>${escapeHtml(
    latest.level || '-'
  )}</td></tr><tr><td>Total Pertemuan</td><td>${
    att.length
  }</td></tr></tbody></table></div></div><div class="docSection"><h3>Rekap Kehadiran</h3><table class="docTable"><thead><tr><th>Hadir</th><th>Izin</th><th>Sakit</th><th>Alpha</th><th>Terlambat</th><th>Reschedule</th></tr></thead><tbody><tr><td>${
    attendanceSummary.Hadir
  }</td><td>${attendanceSummary.Izin}</td><td>${
    attendanceSummary.Sakit
  }</td><td>${attendanceSummary.Alpha}</td><td>${
    attendanceSummary.Terlambat
  }</td><td>${
    attendanceSummary.Reschedule
  }</td></tr></tbody></table></div><div class="docSection"><h3>Capaian Perkembangan Calistung</h3><table class="docTable"><thead><tr><th>Aspek</th><th>Nilai</th><th>Level</th><th>Catatan</th></tr></thead><tbody>${aspectRows}</tbody></table></div><div class="docBox docSection"><b>Catatan Perkembangan Guru</b><p>${escapeHtml(
    narrative
  )}</p></div><div class="docBox docSection"><b>Materi dan Rekomendasi Latihan</b><p><b>Materi terakhir:</b> ${escapeHtml(
    latestLearning.material || '-'
  )}</p><p><b>Latihan rumah:</b> ${escapeHtml(
    latestLearning.homework ||
      'Latihan singkat 5–10 menit secara rutin dengan pendampingan orang tua.'
  )}</p></div><div class="docSign"><div>Orang Tua/Wali<br><br><br><b>(........................)</b></div><div>Guru Les<br><br><br><b>(${escapeHtml(
    settings.teacherName || 'Nama Guru'
  )})</b></div></div>${docFooter()}</div>`;
}

/** Dipakai Pusat Dokumen: lembar absensi 1 pertemuan (landscape) */
export async function documentAttendanceSheetHTML(
  classId,
  date,
  sessionNo,
  classStudents,
  attendanceRows,
  settings
) {
  const statuses = [
    'Hadir',
    'Izin',
    'Sakit',
    'Alpha',
    'Terlambat',
    'Reschedule',
  ];
  const getRecord = (studentId) =>
    attendanceRows.find(
      (a) =>
        a.date === date &&
        String(a.classId || '') === String(classId || '') &&
        a.studentId === studentId
    );
  const rows = classStudents
    .map((s, i) => {
      const rec = getRecord(s.id) || {};
      return `<tr><td>${i + 1}</td><td class="name"><b>${escapeHtml(
        s.name || '-'
      )}</b></td>${statuses
        .map((st) => `<td>${rec.status === st ? '✓' : ''}</td>`)
        .join('')}<td>${escapeHtml(rec.notes || '')}</td></tr>`;
    })
    .join('');
  return `<div class="docPaper landscape wide">${brandedDocHeader(
    settings,
    'LEMBAR ABSENSI KELAS',
    `${fmtDate(date)} · Pertemuan ${sessionNo}`
  )}<div class="docSection"><table class="docTable attendanceDoc"><thead><tr><th>No</th><th class="name">Nama Siswa</th>${statuses
    .map((s) => `<th>${s}</th>`)
    .join('')}<th>Catatan</th></tr></thead><tbody>${
    rows || '<tr><td colspan="9">Belum ada siswa.</td></tr>'
  }</tbody></table></div><div class="docSign"><div>Koordinator/Guru<br><br><br><b>(${escapeHtml(
    settings.teacherName || 'Nama Guru'
  )})</b></div><div>Mengetahui<br><br><br><b>(........................)</b></div></div>${docFooter()}</div>`;
}

/** Dipakai Pusat Dokumen: legger bulanan horizontal (landscape) */
export async function documentLedgerHTML(
  month,
  classStudents,
  attendanceRows,
  settings,
  statusCode
) {
  const [y, m] = month.split('-').map(Number);
  const days = new Date(y, m, 0).getDate();
  const head = Array.from({ length: days }, (_, i) => `<th>${i + 1}</th>`).join(
    ''
  );
  const rows = classStudents
    .map((s, i) => {
      let hadir = 0,
        non = 0,
        cells = '';
      for (let d = 1; d <= days; d++) {
        const date = `${month}-${String(d).padStart(2, '0')}`;
        const rec = attendanceRows.find(
          (a) => a.date === date && a.studentId === s.id
        );
        const code = rec ? statusCode(rec.status) : '';
        if (rec?.status === 'Hadir') hadir++;
        else if (rec?.status) non++;
        cells += `<td>${code}</td>`;
      }
      return `<tr><td>${i + 1}</td><td class="name"><b>${escapeHtml(
        s.name || '-'
      )}</b></td>${cells}<td><b>${hadir}</b></td><td><b>${non}</b></td></tr>`;
    })
    .join('');
  return `<div class="docPaper landscape wide">${brandedDocHeader(
    settings,
    'LEGGER ABSENSI BULANAN',
    month
  )}<div class="docSection"><table class="docTable attendanceDoc"><thead><tr><th>No</th><th class="name">Nama Siswa</th>${head}<th>H</th><th>Non</th></tr></thead><tbody>${
    rows || `<tr><td colspan="${days + 4}">Belum ada siswa.</td></tr>`
  }</tbody></table><p class="muted">Keterangan: H=Hadir, I=Izin, S=Sakit, A=Alpha, T=Terlambat, R=Reschedule.</p></div>${docFooter()}</div>`;
}
